{% set name = "runthis-server" %}

package:
  name: {{ name|lower }}
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  git_url: ../
  version: {{ version }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: {{ environ.get('GIT_BUILD_STR', '') }}
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - ruamel.yaml
    - quart

test:
  imports:
    - runthis.server
  commands:
    - runthis-server --help
    - pytest
  requires:
    - pytest

about:
  home: https://github.com/regro/runthis-server
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - scopatz

